name: octapreview
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  google_sign_in: ^6.3.0
  flutter_staggered_animations: ^1.1.1
#  emoji_picker_flutter: ^1.6.1
  provider: ^6.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^3.3.0
  uuid: ^3.0.7
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/customimages/